meta:
  # override this in your stub to set the environment name,
  # which is used for the deployment name
  #
  # i.e. cf-tabasco
  environment: ~

name: (( grab meta.environment ))

releases:
  - name: cf
    version: latest
  - name: nginx
    version: latest
  - name: diego
    version: 0.1441.0
  - name: garden-linux
    version: 0.327.0
  - name: etcd
    version: 18

compilation:
  workers: 6
  network: cf1
  reuse_compilation_vms: true

update:
  canaries: 1
  max_in_flight: 1
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: true
