properties:
  acceptance_tests:
    api: (( grab meta.api_domain ))
    apps_domain: (( grab properties.app_domains[0] ))
    system_domain: (( grab properties.system_domain ))
    admin_user: "admin"
    admin_password: (( grab secrets.uaa_admin_password ))
    skip_ssl_validation: false
    backend: "diego"
    client_secret: (( grab secrets.uaa_clients_gorouter_secret ))
    skip_diego_unsupported_tests: true
    include_tasks: true
    include_v3: true
    include_security_groups: true
    include_routing: true
    skip_regex: 'routing.API|allows\spreviously-blocked\sip|Adding\sa\swildcard\sroute\sto\sa\sdomain|forwards\sapp\smessages\sto\sregistered\ssyslog\sdrains'
    include_internet_dependent: true
    include_logging: true
    include_operator: true
    include_services: true
    include_route_services: false

  smoke_tests:
    api: (( grab meta.api_domain ))
    apps_domain: (( grab properties.app_domains[0] ))
    user: "admin"
    password: (( grab secrets.uaa_admin_password ))
    org: "SMOKE_TESTS"
    space: "SMOKE_TESTS"
    use_existing_org: false
    use_existing_space: false
    skip_ssl_validation: false
