meta:
  api_domain: (( concat "api." properties.domain ))

  release:
    name: cf

  logsearch_shipper:
    release:
      name: "logsearch-shipper"

  api_consul_services:
    cloud_controller_ng: {}

  api_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: cloud_controller_ng
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: statsd-injector
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))
  - name: java-buildpack
    release: (( grab meta.release.name ))
  - name: java-offline-buildpack
    release: (( grab meta.release.name ))
  - name: go-buildpack
    release: (( grab meta.release.name ))
  - name: binary-buildpack
    release: (( grab meta.release.name ))
  - name: nodejs-buildpack
    release: (( grab meta.release.name ))
  - name: ruby-buildpack
    release: (( grab meta.release.name ))
  - name: php-buildpack
    release: (( grab meta.release.name ))
  - name: python-buildpack
    release: (( grab meta.release.name ))
  - name: staticfile-buildpack
    release: (( grab meta.release.name ))

  api_worker_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: cloud_controller_worker
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  clock_templates:
  - name: cloud_controller_clock
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  consul_templates:
  - name: consul_agent
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  etcd_templates:
  - name: consul_agent
    release: (( grab meta.release.name ))
  - name: etcd
    release: etcd
  - name: etcd_metrics_server
    release: etcd
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  loggregator_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: doppler
    release: (( grab meta.release.name ))
  - name: syslog_drain_binder
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  loggregator_trafficcontroller_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: loggregator_trafficcontroller
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  nats_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: nats
    release: (( grab meta.release.name ))
  - name: nats_stream_forwarder
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))

  router_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: gorouter
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))
  - name: haproxy
    release: paas-haproxy

  stats_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: collector
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  uaa_templates:
  - name: consul_agent
    release: (( grab meta.consul_templates.consul_agent.release ))
  - name: uaa
    release: (( grab meta.release.name ))
  - name: metron_agent
    release: (( grab meta.release.name ))
  - name: statsd-injector
    release: (( grab meta.release.name ))
  - name: logsearch-shipper
    release: (( grab meta.logsearch_shipper.release.name ))

  diego_job_templates:
    brain:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: converger
        release: diego
      - name: metron_agent
        release: cf
    cell:
      - name: consul_agent
        release: cf
      - name: rep
        release: diego
      - name: garden
        release: garden-linux
      - name: rootfses
        release: diego
      - name: metron_agent
        release: cf
    cc_bridge:
      - name: consul_agent
        release: cf
      - name: stager
        release: diego
      - name: nsync
        release: diego
      - name: tps
        release: diego
      - name: cc_uploader
        release: diego
      - name: metron_agent
        release: cf
    route_emitter:
      - name: consul_agent
        release: cf
      - name: route_emitter
        release: diego
      - name: metron_agent
        release: cf
    access:
      - name: consul_agent
        release: cf
      - name: ssh_proxy
        release: diego
      - name: metron_agent
        release: cf
      - name: file_server
        release: diego
    database:
      - name: consul_agent
        release: cf
      - name: bbs
        release: diego
      - name: metron_agent
        release: cf
    colocated:
      - name: consul_agent
        release: cf
      - name: auctioneer
        release: diego
      - name: bbs
        release: diego
      - name: cc_uploader
        release: diego
      - name: converger
        release: diego
      - name: file_server
        release: diego
      - name: metron_agent
        release: cf
      - name: nsync
        release: diego
      - name: route_emitter
        release: diego
      - name: ssh_proxy
        release: diego
      - name: stager
        release: diego
      - name: tps
        release: diego

jobs:
  - name: consul_z1
    templates: (( grab meta.consul_templates ))
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(27, 28, 29) ))
    update:
      serial: true
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: ""

  - name: consul_z2
    templates: (( grab meta.consul_templates ))
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(27, 28, 29) ))
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: ""

  - name: nats_z1
    templates: (( grab meta.nats_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(1) ))
    properties:
      metron_agent:
        zone: ""

  - name: nats_z2
    templates: (( grab meta.nats_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(1) ))
    properties:
      metron_agent:
        zone: ""

  - name: etcd_z1
    templates: (( grab meta.etcd_templates ))
    instances: 1
    persistent_disk: 10024
    resource_pool: medium_z1
    networks:
      - name: cf1
        static_ips: (( static_ips(9) ))
    update:
      serial: true
    properties:
      metron_agent:
        zone: ""
      consul:
        agent:
          services:
            etcd: {}

  - name: etcd_z2
    templates: (( grab meta.etcd_templates ))
    instances: 1
    persistent_disk: 10024
    resource_pool: medium_z2
    networks:
      - name: cf2
        static_ips: (( static_ips(9) ))
    update:
      serial: true
    properties:
      metron_agent:
        zone: ""
      consul:
        agent:
          services:
            etcd: {}

  - name: consul_z3
    templates: (( grab meta.consul_templates ))
    instances: 1
    persistent_disk: 1024
    resource_pool: small_z3
    networks:
      - name: cf3
        static_ips: (( static_ips(27, 28, 29) ))
    properties:
      consul:
        agent:
          mode: server
      metron_agent:
        zone: ""

  - name: etcd_z3
    templates: (( grab meta.etcd_templates ))
    instances: 1
    persistent_disk: 10024
    resource_pool: medium_z3
    networks:
      - name: cf3
        static_ips: (( static_ips(9) ))
    properties:
      metron_agent:
        zone: ""
      consul:
        agent:
          services:
            etcd: {}

  - name: stats_z1
    templates: (( grab meta.stats_templates ))
    instances: 1
    resource_pool: small_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: uaa_z1
    templates: (( grab meta.uaa_templates ))
    instances: 1
    resource_pool: uaa_z1
    networks:
      - name: cf1
    properties:
      consul:
        agent:
          services:
            uaa: {}
      metron_agent:
        zone: ""

  - name: uaa_z2
    templates: (( grab meta.uaa_templates ))
    instances: 1
    resource_pool: uaa_z2
    networks:
      - name: cf2
    properties:
      consul:
        agent:
          services:
            uaa: {}
      metron_agent:
        zone: ""

  - name: api_z1
    templates: (( grab meta.api_templates ))
    instances: 1
    resource_pool: api_z1
    networks:
      - name: cf1
    properties:
      consul:
        agent:
          services: (( grab meta.api_consul_services ))
      metron_agent:
        zone: ""

  - name: api_z2
    templates: (( grab meta.api_templates ))
    instances: 1
    resource_pool: api_z2
    networks:
      - name: cf2
    properties:
      consul:
        agent:
          services: (( grab meta.api_consul_services ))
      metron_agent:
        zone: ""

  - name: clock_global
    templates: (( grab meta.clock_templates ))
    instances: 1
    resource_pool: clock_global
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: api_worker_z1
    templates: (( grab meta.api_worker_templates ))
    instances: 1
    resource_pool: api_worker_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: api_worker_z2
    templates: (( grab meta.api_worker_templates ))
    instances: 1
    resource_pool: api_worker_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""

  - name: doppler_z1
    templates: (( grab meta.loggregator_templates ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      doppler:
        zone: z1
      metron_agent:
        zone: ""

  - name: doppler_z2
    templates: (( grab meta.loggregator_templates ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      doppler:
        zone: z2
      metron_agent:
        zone: ""

  - name: loggregator_trafficcontroller_z1
    templates: (( grab meta.loggregator_trafficcontroller_templates ))
    instances: 1
    resource_pool: loggregator_trafficcontroller_z1
    networks:
      - name: cf1
    properties:
      traffic_controller:
        zone: z1
      metron_agent:
        zone: ""

  - name: loggregator_trafficcontroller_z2
    templates: (( grab meta.loggregator_trafficcontroller_templates ))
    instances: 1
    resource_pool: loggregator_trafficcontroller_z2
    networks:
      - name: cf2
    properties:
      traffic_controller:
        zone: z2
      metron_agent:
        zone: ""

  - name: router_z1
    templates: (( grab meta.router_templates ))
    instances: 1
    resource_pool: router_z1
    networks:
      - name: router1
        static_ips: (( static_ips(1, 2 ,3 ,4, 5, 6, 7, 8) ))
    properties:
      consul:
        agent:
          services:
            gorouter: {}
      metron_agent:
        zone: ""

  - name: router_z2
    templates: (( grab meta.router_templates ))
    instances: 1
    resource_pool: router_z2
    networks:
      - name: router2
        static_ips: (( static_ips(1, 2 ,3 ,4, 5, 6, 7, 8) ))
    properties:
      consul:
        agent:
          services:
            gorouter: {}
      metron_agent:
        zone: ""

# Diego

  - name: access_z1
    templates: (( grab meta.diego_job_templates.access ))
    instances: 0
    resource_pool: access_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: access_z2
    templates: (( grab meta.diego_job_templates.access ))
    instances: 0
    resource_pool: access_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""

  - name: brain_z1
    templates: (( grab meta.diego_job_templates.brain ))
    instances: 0
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: brain_z2
    templates: (( grab meta.diego_job_templates.brain ))
    instances: 0
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""

  - name: cc_bridge_z1
    templates: (( grab meta.diego_job_templates.cc_bridge ))
    instances: 0
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: cc_bridge_z2
    templates: (( grab meta.diego_job_templates.cc_bridge ))
    instances: 0
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""

  - name: cell_z1
    templates: (( grab meta.diego_job_templates.cell ))
    instances: (( grab meta.cell_z1.instances ))
    resource_pool: cell_z1
    networks:
      - name: cell1
    properties:
      metron_agent:
        zone: ""
      diego:
        rep:
          zone: z1

  - name: cell_z2
    templates: (( grab meta.diego_job_templates.cell ))
    instances: (( grab meta.cell_z2.instances ))
    resource_pool: cell_z2
    networks:
      - name: cell2
    properties:
      metron_agent:
        zone: ""
      diego:
        rep:
          zone: z2

  - name: colocated_z1
    templates: (( grab meta.diego_job_templates.colocated ))
    instances: 1
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      diego:
        rep:
          zone: z1
      metron_agent:
        zone: ""

  - name: colocated_z2
    templates: (( grab meta.diego_job_templates.colocated ))
    instances: 1
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      diego:
        rep:
          zone: z2
      metron_agent:
        zone: ""

  - name: database_z1
    templates: (( grab meta.diego_job_templates.database ))
    instances: 0
    resource_pool: database_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: database_z2
    templates: (( grab meta.diego_job_templates.database ))
    instances: 0
    resource_pool: database_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""

  - name: route_emitter_z1
    templates: (( grab meta.diego_job_templates.route_emitter ))
    instances: 0
    resource_pool: medium_z1
    networks:
      - name: cf1
    properties:
      metron_agent:
        zone: ""

  - name: route_emitter_z2
    templates: (( grab meta.diego_job_templates.route_emitter ))
    instances: 0
    resource_pool: medium_z2
    networks:
      - name: cf2
    properties:
      metron_agent:
        zone: ""
