meta:
  graphite_templates:
    - name: consul_agent
      release: (( grab meta.consul_templates.consul_agent.release ))
    - name: datadog-consul
      release: datadog-for-cloudfoundry
    - name: metron_agent
      release: cf
    - name: carbon
      release: graphite
    - name: graphite-web
      release: graphite
    - name: statsd
      release: graphite
    - name: grafana
      release: grafana

releases:
- name: graphite
  version: commit-829b5920f4343cb9929c5fc219dfc4413a772e63
- name: grafana
  version: 5
  url: https://bosh.io/d/github.com/vito/grafana-boshrelease?v=5
  sha1: 0edd89d7b383a2556a79f6688f576aa4b6f33bc2

jobs:
- name: graphite
  azs: [z1]
  instances: 1
  vm_type: graphite
  stemcell: default
  persistent_disk_type: graphite_data
  networks:
    - name: cf
      static_ips:
        # This IP is replicated in manifests/shared/deployments/collectd.yml:38
        # because grab cannot be used to interpolate in a multi-line string.
        - 10.0.16.20
  properties:
    statsd:
      deleteIdleStats: true
    carbon:
      prune_delay: 10
      filter:
        enable: true
        blacklist:
        - stats\.counters\.cfstats\.router_.+\.[0-9]+\.http\..+\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*
      storage_schemas:
        - name: "catch_all"
          pattern: "^.*$"
          retentions: "10s:1d,1m:7d,15m:30d,1h:1y,1d:5y"
      storage_aggregations:
        - name: "catch_all"
          pattern: "^.*$"
          xFilesFactor: "0.5"
          aggregationMethod: "average"
      cache:
        max_creates_per_minute: 500
    graphite-web:
      time_zone: Europe/London
      httpd:
        port: 3001
      wsgi:
        inactivity-timeout: 60
    grafana:
      root_url: "/"
      admin_username: "admin"
      admin_password: (( grab secrets.grafana_admin_password ))
      datasources:
        - name: graphite
          type: graphite
          url: http://localhost:3001
    tags:
      job: graphite
      tags: (( inject meta.datadog_tags ))

  templates: (( grab meta.graphite_templates ))
