releases:
- name: graphite
  version: 0.1.1
  url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/graphite-0.1.1.tgz
  sha1: 7ce15711ae9afc04ccf152bab3f7de9b234f7c4f
- name: grafana
  version: 0.1.2
  url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/grafana-0.1.2.tgz
  sha1: 483ee4a07d683c94014efede103dd93cb92cd883

instance_groups:
- name: graphite
  azs: [z1]
  instances: 1
  vm_type: graphite
  stemcell: default
  persistent_disk_type: graphite_data
  networks:
    - name: cf
      static_ips:
        # This IP is replicated in manifests/shared/deployments/collectd.yml:38
        # because grab cannot be used to interpolate in a multi-line string.
        - 10.0.16.20
  properties:
    statsd:
      deleteIdleStats: true
    carbon:
      prune_delay: 10
      filter:
        enable: true
        blacklist:
        - stats\.counters\.cfstats\.router_.+\.[0-9]+\.http\..+\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}.*
      storage_schemas:
        - name: "catch_all"
          pattern: "^.*$"
          retentions: "10s:1d,1m:7d,15m:30d,1h:1y,1d:5y"
      storage_aggregations:
        - name: "catch_all"
          pattern: "^.*$"
          xFilesFactor: "0.5"
          aggregationMethod: "average"
      cache:
        max_creates_per_minute: 500
    graphite-web:
      time_zone: Europe/London
      httpd:
        port: 3001
      wsgi:
        inactivity-timeout: 60
    grafana:
      root_url: "/"
      admin_username: "admin"
      admin_password: ((secrets_grafana_admin_password))
      datasources:
        - name: graphite
          type: graphite
          url: http://localhost:3001

  jobs:
    - name: carbon
      release: graphite
    - name: graphite-web
      release: graphite
    - name: statsd
      release: graphite
    - name: grafana
      release: grafana
