releases:
  - name: cdn-broker
    version: 0.1.6
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/cdn-broker-0.1.6.tgz
    sha1: 7db1bf1d80707e56d257d813d5155ce3c6767127

instance_groups:
  - name: cdn_broker
    azs: [z1, z2]
    instances: 2
    vm_type: cdn_broker
    stemcell: default
    jobs:
      - name: cdn-broker
        release: cdn-broker
      - name: cdn-cron
        release: cdn-broker
      - name: datadog-cdn-broker
        release: datadog-for-cloudfoundry
    networks:
      - name: cf
    properties:
      cdn-broker:
        broker_username: "cdn-broker"
        broker_password: ((secrets_cdn_broker_admin_password))
        database_url: ((terraform_outputs_cdn_db_connection_string))
        email: "the-multi-cloud-paas-team@digital.cabinet-office.gov.uk"
        acme_url: "https://acme-v01.api.letsencrypt.org/directory"
        bucket: gds-paas-((environment))-cdn-broker-challenge
        iam_path_prefix: ((environment))-letsencrypt
        cloudfront_prefix: ((environment))-cdn
        aws_access_key_id: ""
        aws_secret_access_key: ""
        aws_default_region: "eu-west-1"
        api_address: https://api.((terraform_outputs_cf_root_domain))
        client_id: "cdn_broker"
        client_secret: ((secrets_uaa_clients_cdn_broker_secret))
        default_origin: ((terraform_outputs_cf_apps_domain))
