releases:
  - name: cdn-broker
    version: 0.1.5
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/cdn-broker-0.1.5.tgz
    sha1: 9d0cef5c10677fa9d9bf921c8af36e205ad910ab

jobs:
  - name: cdn_broker
    azs: [z1, z2]
    instances: 2
    vm_type: cdn_broker
    stemcell: default
    templates:
      - name: cdn-broker
        release: cdn-broker
      - name: cdn-cron
        release: cdn-broker
      - name: datadog-cdn-broker
        release: datadog-for-cloudfoundry
    networks:
      - name: cf
    properties:
      cdn-broker:
        broker_username: "cdn-broker"
        broker_password: (( grab secrets.cdn_broker_admin_password ))
        database_url: (( grab terraform_outputs.cdn_db_connection_string ))
        email: "the-multi-cloud-paas-team@digital.cabinet-office.gov.uk"
        acme_url: "https://acme-v01.api.letsencrypt.org/directory"
        bucket: (( concat "gds-paas-" meta.environment "-cdn-broker-challenge" ))
        iam_path_prefix: (( concat meta.environment "-letsencrypt" ))
        cloudfront_prefix: (( concat meta.environment "-cdn" ))
        aws_access_key_id: ""
        aws_secret_access_key: ""
        aws_default_region: "eu-west-1"
        api_address: (( concat "https://api." terraform_outputs.cf_root_domain ))
        client_id: "cdn_broker"
        client_secret: (( grab secrets.uaa_clients_cdn_broker_secret ))
        default_origin: (( grab terraform_outputs.cf_apps_domain ))
