---

defaults: &defaults
  platform_fee: "0.40"
  app_cost_per_gb_hour: "0.01"
  compose_mongodb_tiny: "((1936.57/(48*1024))/30/24)"
  compose_elasticsearh_tiny: "((1936.57/(48*1024))/30/24)"
  compose_redis_tiny: "((1936.57/(48*1024))/30/24)"
  aiven_elasticsearch_startup_4: "0.178"
  aiven_elasticsearch_business_4: "0.548"
  aiven_elasticsearch_business_8: "1.096"
  aiven_elasticsearch_business_16: "2.192"

eu-west-1:
  <<: *defaults
  rds_storage: "0.127"
  rds_storage_ha: "0.253"

  # Postgres pricing
  rds_pg_t2_micro: "0.02"
  rds_pg_t2_small: "0.039"
  rds_pg_t2_small_ha: "0.078"
  rds_pg_t3_micro: "0.02"
  rds_pg_t3_small: "0.039"
  rds_pg_t3_small_ha: "0.078"

  rds_pg_m4_large: "0.201"
  rds_pg_m4_large_ha: "0.402"
  rds_pg_m4_2xlarge: "0.806"
  rds_pg_m4_2xlarge_ha: "1.612"
  rds_pg_m4_4xlarge: "1.612"
  rds_pg_m4_4xlarge_ha: "3.224"
  rds_pg_m5_large: "0.197"
  rds_pg_m5_large_ha: "0.394"
  rds_pg_m5_2xlarge: "0.788"
  rds_pg_m5_2xlarge_ha: "1.576"
  rds_pg_m5_4xlarge: "1.576"
  rds_pg_m5_4xlarge_ha: "3.152"

  # MySQL pricing
  rds_mysql_t2_micro: "0.018"
  rds_mysql_t2_small: "0.036"
  rds_mysql_t2_small_ha: "0.072"
  rds_mysql_t3_micro: "0.018"
  rds_mysql_t3_small: "0.036"
  rds_mysql_t3_small_ha: "0.072"

  rds_mysql_m4_large: "0.193"
  rds_mysql_m4_large_ha: "0.386"
  rds_mysql_m4_2xlarge: "0.772"
  rds_mysql_m4_2xlarge_ha: "1.544"
  rds_mysql_m4_4xlarge: "1.545"
  rds_mysql_m4_4xlarge_ha: "3.09"
  rds_mysql_m5_large: "0.189"
  rds_mysql_m5_large_ha: "0.378"
  rds_mysql_m5_2xlarge: "0.756"
  rds_mysql_m5_2xlarge_ha: "1.512"
  rds_mysql_m5_4xlarge: "1.512"
  rds_mysql_m5_4xlarge_ha: "3.024"

  elasticache_t2_micro: "0.018"
  elasticache_t2_small: "0.036"
  elasticache_t2_medium: "0.073"
  elasticache_m5_large: "0.172"
  s3_bucket_default: "0.00685"

eu-west-2:
  <<: *defaults
  rds_storage: "0.133"
  rds_storage_ha: "0.266"

  # Postgres pricing
  rds_pg_t2_micro: "0.021"
  rds_pg_t2_small: "0.041"
  rds_pg_t2_small_ha: "0.082"
  rds_pg_t3_micro: "0.021"
  rds_pg_t3_small: "0.041"
  rds_pg_t3_small_ha: "0.082"

  rds_pg_m4_large: "0.211"
  rds_pg_m4_large_ha: "0.422"
  rds_pg_m4_2xlarge: "0.846"
  rds_pg_m4_2xlarge_ha: "1.693"
  rds_pg_m4_4xlarge: "1.693"
  rds_pg_m4_4xlarge_ha: "3.385"
  rds_pg_m5_large: "0.206"
  rds_pg_m5_large_ha: "0.412"
  rds_pg_m5_2xlarge: "0.824"
  rds_pg_m5_2xlarge_ha: "1.648"
  rds_pg_m5_4xlarge: "1.648"
  rds_pg_m5_4xlarge_ha: "3.296"

  # MySQL pricing
  rds_mysql_t2_micro: "0.019"
  rds_mysql_t2_small: "0.038"
  rds_mysql_t2_small_ha: "0.076"
  rds_mysql_t3_micro: "0.019"
  rds_mysql_t3_small: "0.038"
  rds_mysql_t3_small_ha: "0.076"

  rds_mysql_m4_large: "0.203"
  rds_mysql_m4_large_ha: "0.405"
  rds_mysql_m4_2xlarge: "0.811"
  rds_mysql_m4_2xlarge_ha: "1.621"
  rds_mysql_m4_4xlarge: "1.622"
  rds_mysql_m4_4xlarge_ha: "3.245"
  rds_mysql_m5_large: "0.198"
  rds_mysql_m5_large_ha: "0.396"
  rds_mysql_m5_2xlarge: "0.792"
  rds_mysql_m5_2xlarge_ha: "1.584"
  rds_mysql_m5_4xlarge: "1.584"
  rds_mysql_m5_4xlarge_ha: "3.168"


  elasticache_t2_micro: "0.019"
  elasticache_t2_small: "0.038"
  elasticache_t2_medium: "0.077"
  elasticache_m5_large: "0.18"
  s3_bucket_default: "0.00685"
