# Source: paas-metrics
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: AivenEstimatedCostHigh
    rules:
      - alert: AivenEstimatedCostHigh
        expr: paas_aiven_estimated_cost_pounds > 6500
        for: 1h
        labels:
          severity: critical
        annotations:
          summary: "Aiven estimated cost is high, possibly need to alert finance."
          description: "The estimated monthly cost of Aiven is currently Â£{{ $value | printf \"%.2f\" }}, possibly need to alert finance."
