# Source: bosh-exporter
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: BoshHighCPUUtilisation
    rules:
      - record: "bosh_job:bosh_job_cpu:avg1h"
        expr: avg_over_time(bosh_job_cpu_sys{bosh_job_name!="diego-cell",bosh_job_name!="concourse"}[1h]) + avg_over_time(bosh_job_cpu_user{bosh_job_name!="diego-cell",bosh_job_name!="concourse"}[1h]) + avg_over_time(bosh_job_cpu_wait{bosh_job_name!="diego-cell",bosh_job_name!="concourse"}[1h])

      - alert: BoshHighCPUUtilisation
        expr: "bosh_job:bosh_job_cpu:avg1h > 70"
        labels:
          severity: warning
        annotations:
          summary: "High cpu utilisation on {{ $labels.bosh_job_name }}/{{ $labels.bosh_job_index }}"
          description: "{{ $labels.bosh_job_name }}/{{ $labels.bosh_job_index }} CPU utilisation was over {{ $value | printf \"%.0f\" }}% in the last hour on average"

# FIXME: there is no easy way currently to remove upstream alerts
# This effectively disables the upstream CPU alert by increasing the threshold to a really high value
# If a node has a really high load for a long time it's still useful to know about it
- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=bosh_alerts/properties?/bosh_alerts/job_high_cpu_load
  value:
    threshold: 50
    evaluation_time: 1h
