# Source: paas-metrics
---

- type: replace
  path: /instance_groups/name=prometheus2/jobs/name=prometheus2/properties/prometheus/custom_rules?/-
  value:
    name: ElasticacheParamGroupCountCloseToLimit
    rules:
      - alert: ElasticacheParamGroupCountCloseToLimit
        expr: paas_aws_elasticache_cache_parameter_group_count > ((aws_limits_elasticache_cache_parameter_groups)) / 100 * 80
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "Number of elasticache cache parameter groups is close to the limit"
          description: "We are using {{ $value | printf \"%.0f\" }} of ((aws_limits_elasticache_cache_parameter_groups)) Elasticache parameter groups. We might have to contact AWS support to raise the limit."
