releases:
  - name: os-conf
    version: commit-a2bc2ab32248c8edf7c4790b33902893b1f4db66
  - name: collectd
    version: 0.3

addons:
  - name: os-configuration
    jobs:
    - name: set_mtu
      release: os-conf
  - name: collectd
    jobs:
    - name: collectd
      release: collectd
    properties:
      collectd: (( grab meta.collectd ))
