---
releases:
- name: datadog-agent
  version: 0.1.1
  url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-agent-0.1.1.tgz
  sha1: 71c6e2f957b4381d44dedce1b1080cbfc5e8ef28

meta:
  datadog:
    enabled: (( grab $ENABLE_DATADOG ))
    api_key: (( grab $DATADOG_API_KEY || "undefined" ))
    application_key: (( grab $DATADOG_APP_KEY || "undefined" ))
    use_dogstatsd: false
    include_bosh_tags: true
    tags:
      aws_account: (( grab $AWS_ACCOUNT ))
      deploy_env: (( grab terraform_outputs.environment ))
