releases:
# When updating the version of the CPI here, the version used in the
# bosh-init container must also be updated so that the cached CPI compile
# will be used.
- name: bosh-aws-cpi
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=52
  sha1: dc4a0cca3b33dce291e4fbeb9e9948b6a7be3324


jobs:
- name: bosh
  templates:
  - {name: registry, release: bosh}
  - {name: aws_cpi, release: bosh-aws-cpi}

cloud_provider:
  template:
    name: aws_cpi
    release: bosh-aws-cpi

  properties:
    aws: (( grab meta.aws.cloud_provider ))

