meta:
  aws:
    common:
      default_key_name: (( grab terraform_outputs.key_pair_name ))
      default_security_groups:
      - (( grab terraform_outputs.default_security_group ))
      region: (( grab terraform_outputs.region ))
    cloud_provider:
      credentials_source: env_or_profile
      default_key_name: (( grab meta.aws.common.default_key_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      region: (( grab meta.aws.common.region ))
      max_retries: 8
    bosh_properties:
      credentials_source: env_or_profile
      default_key_name: (( grab meta.aws.common.default_key_name ))
      default_security_groups: (( grab meta.aws.common.default_security_groups ))
      default_iam_instance_profile: bosh-managed
      region: (( grab meta.aws.common.region ))
      max_retries: 8

  bosh_private_ip: (( grab terraform_outputs.microbosh_static_private_ip ))
  bosh_public_ip: (( grab terraform_outputs.microbosh_static_public_ip ))
  bosh_service_ip: (( grab meta.bosh_private_ip ))

  ntp:
  - 0.pool.ntp.org
  - 1.pool.ntp.org


jobs:
- name: bosh
  properties:
    hm:
      resurrector_enabled: true
    aws: (( grab meta.aws.bosh_properties ))
    dns: null


