---
cell_instances: 3
router_instances: 2
api_instances: 2
doppler_instances: 6
log_api_instances: 2
scheduler_instances: 2
cc_worker_instances: 2
cc_hourly_rate_limit: 15000
paas_region_name: dev

prometheus_disk_size: 100GB
prometheus_retention_size: 90GB
