---
uaa_instances: 3
nats_instances: 3
diego_api_instances: 3
cell_instances: 36
router_instances: 18
api_instances: 6
doppler_instances: 33
log_api_instances: 6
scheduler_instances: 4
cc_worker_instances: 4
cc_hourly_rate_limit: 20000
cc_staging_timeout_in_seconds: 2700
paas_region_name: ireland

prometheus_disk_size: 500GB
prometheus_retention_size: 475GB
