---
cell_instances: 57
router_instances: 6
api_instances: 12
doppler_instances: 33
log_api_instances: 6
scheduler_instances: 4
cc_worker_instances: 4
cc_hourly_rate_limit: 20000
paas_region_name: london
