---
uaa_instances: 3
nats_instances: 3
diego_api_instances: 3
cell_instances: 141
router_instances: 30
api_instances: 15
doppler_instances: 45
log_cache_instances: 27
log_api_instances: 27
scheduler_instances: 10
cc_worker_instances: 12
cc_hourly_rate_limit: 60000
cc_staging_timeout_in_seconds: 2700
cc_maximum_health_check_timeout_in_seconds: 300
paas_region_name: london

prometheus_disk_size: 750GB
prometheus_retention_size: 700GB
