---
uaa_instances: 2
nats_instances: 2
diego_api_instances: 2
cell_instances: 6
router_instances: 3
api_instances: 2
doppler_instances: 3
log_api_instances: 3
scheduler_instances: 3
cc_worker_instances: 2
cc_hourly_rate_limit: 100000
cc_staging_timeout_in_seconds: 1800
paas_region_name: staging

prometheus_disk_size: 500GB
prometheus_retention_size: 475GB
