buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.43
  sha: 50a4af12021d0c37807b3a419e84b776b132ae5f8548c12e900880056b312b33
  filename: binary-buildpack-cflinuxfs3-v1.0.43.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.43/binary-buildpack-cflinuxfs3-v1.0.43.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.3.41
  sha: bb4a54bd80d2e52e6762eec8b2dbe0505bd3960e5c1e7c8a56fbc8dff0bc1e3b
  filename: dotnet-core-buildpack-cflinuxfs3-v2.3.41.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.3.41/dotnet-core-buildpack-cflinuxfs3-v2.3.41.zip
  dependencies:
  - name: bower
    version: 1.8.14
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 5.0.15
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 6.0.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.1.23
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 5.0.15
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 6.0.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.1.417
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 5.0.406
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 6.0.201
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "6.1"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.6.2
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 16.14.2
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.9.42
  sha: e02d855294f4950869c3d0489330d354bd4779585d9f5edf914612df5e208158
  filename: go-buildpack-cflinuxfs3-v1.9.42.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.9.42/go-buildpack-cflinuxfs3-v1.9.42.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.17.7
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.17.8
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: "1.18"
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.48.2
  sha: aebf10c93015e469bb67cba84ac87541f6acb220e97ac005b6e6be30e5b4db32
  filename: java-buildpack-v4.48.2.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.48.2/java-buildpack-v4.48.2.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.7.69
  sha: 21b152fbbcc939ded59381621514e7f199f838309b86ab067d4b515339a394b8
  filename: nodejs-buildpack-cflinuxfs3-v1.7.69.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.7.69/nodejs-buildpack-cflinuxfs3-v1.7.69.zip
  dependencies:
  - name: node
    version: 12.22.10
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.22.12
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.19.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 14.19.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 16.14.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 16.14.2
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.18
    cf_stacks:
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.4.59
  sha: e6e1192d0d6757a7049ab7a86de90c54866076f67320db4712b4c6a138d988e7
  filename: php-buildpack-cflinuxfs3-v4.4.59.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.4.59/php-buildpack-cflinuxfs3-v4.4.59.zip
  dependencies:
  - name: CAAPM
    version: 20.11.0
    cf_stacks:
    - cflinuxfs3
  - name: appdynamics
    version: 22.3.0-501
    cf_stacks:
    - cflinuxfs3
  - name: composer
    version: 2.3.4
    cf_stacks:
    - cflinuxfs3
  - name: httpd
    version: 2.4.53
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 9.18.1.303
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.20.2
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.21.6
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.27
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.4.28
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 8.0.16
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 8.0.17
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 8.1.3
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 8.1.4
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.7.53
  sha: 98bc7d6861a9996f2dcf5f6e94e9309bcd2d7c42af6437e2ad5700ea8c721411
  filename: python-buildpack-cflinuxfs3-v1.7.53.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.7.53/python-buildpack-cflinuxfs3-v1.7.53.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs3
  - name: miniconda3-py39
    version: 4.11.0
    cf_stacks:
    - cflinuxfs3
  - name: pip
    version: 22.0.4
    cf_stacks:
    - cflinuxfs3
  - name: pipenv
    version: 2022.3.28
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.12
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.13
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.12
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.8.13
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.9.11
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.9.12
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.10.3
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.10.4
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 62.0.0
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.8.53
  sha: 369f398b1e6ef15e14d441a3f98eb204322ca2dfa3b7833777209a997e72f841
  filename: ruby-buildpack-cflinuxfs3-v1.8.53.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.8.53/ruby-buildpack-cflinuxfs3-v1.8.53.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: bundler
    version: 2.3.11
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.20.1
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.3.4.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 16.14.2
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.4
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.7.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 3.0.2
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 3.0.3
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 3.1.0
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 3.1.1
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.3.11
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.22.18
    cf_stacks:
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.5.29
  sha: fcd3254fe3006b394487f57f1e56a58fe42c72d23ac73574b25482ddf44d00d6
  filename: staticfile-buildpack-cflinuxfs3-v1.5.29.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.5.29/staticfile-buildpack-cflinuxfs3-v1.5.29.zip
  dependencies:
  - name: nginx
    version: 1.20.2
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.21.6
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.1.37
  sha: 8d0a2f611259db18f5c7f3036ff9218d85154b5ed21e99f1795fee2ce1bc24c8
  filename: nginx-buildpack-cflinuxfs3-v1.1.37.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.1.37/nginx-buildpack-cflinuxfs3-v1.1.37.zip
  dependencies:
  - name: nginx
    version: 1.20.2
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.21.6
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.3
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.17.8.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.19.9.1
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.1.28
  sha: c6108efee01ac75127611a61a53f972858505c495d4f4dcd3d034fc8ca5dedb9
  filename: r-buildpack-cflinuxfs3-v1.1.28.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.1.28/r-buildpack-cflinuxfs3-v1.1.28.zip
  dependencies:
  - name: r
    version: 3.6.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.1.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 4.1.3
    cf_stacks:
    - cflinuxfs3
