buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.33
  sha: 9643ee5ee1dfe652b13db68969880882261f18e43e329a58b89e9138a852870d
  filename: binary-buildpack-cflinuxfs3-v1.0.33.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.33/binary-buildpack-cflinuxfs3-v1.0.33.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.2.13
  sha: 0a911b302a5143ac54807b3ccd4ac1984da4d280837938c6ec2ccff841d4be94
  filename: dotnet-core-buildpack-cflinuxfs3-v2.2.13.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.2.13/dotnet-core-buildpack-cflinuxfs3-v2.2.13.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.5
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.5
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.11
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.2.5
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.2.5
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.2.6
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.2.6
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 3.0.0-preview7.19365.7
    cf_stacks:
    - cflinuxfs3
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.0.15
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 1.1.13
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.13
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.5
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.5
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.11
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.2.5
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.2.5
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.2.6
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.2.6
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 3.0.0-preview7-27912-14
    cf_stacks:
    - cflinuxfs3
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.13
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.13
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 1.1.14
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.14
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.403
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.1.403
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.508
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.1.508
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.2.205
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.2.301
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.2.301
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 3.0.100-preview7-012821
    cf_stacks:
    - cflinuxfs3
    - cflinuxfs2
  - name: libgdiplus
    version: "5.6"
    cf_stacks:
    - cflinuxfs2
  - name: libgdiplus
    version: "5.6"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs2
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.15.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.16.0
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.8.42
  sha: e58331dc86919bf96ddabd15c4ea9be97da22605557d60f3d4861ca8157111b9
  filename: go-buildpack-cflinuxfs3-v1.8.42.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.8.42/go-buildpack-cflinuxfs3-v1.8.42.zip
  dependencies:
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs2
  - name: dep
    version: 0.5.4
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs2
  - name: glide
    version: 0.13.3
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.11.11
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.11.11
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.11.12
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.11.12
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.6
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.12.6
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.7
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.12.7
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs2
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.20
  sha: 58036bc99ade005e62df4303a85883eb8bab8c82c01834e7db662e6987c3f251
  filename: java-buildpack-v4.20.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.20/java-buildpack-v4.20.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.6.54
  sha: a0f58426693d54e9e76d818edaf1f6f1623adb9704084c36dcd6e11d9a75efba
  filename: nodejs-buildpack-cflinuxfs3-v1.6.54.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.6.54/nodejs-buildpack-cflinuxfs3-v1.6.54.zip
  dependencies:
  - name: node
    version: 8.16.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 8.16.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 8.16.1
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 8.16.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.14.2
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.15.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.16.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.16.3
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.7.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 12.8.1
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.3.80
  sha: 75ca7a4b711ad49f7703495e68c548e2d914d14c6f04b13cc744463c83307c0d
  filename: php-buildpack-cflinuxfs3-v4.3.80.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.3.80/php-buildpack-cflinuxfs3-v4.3.80.zip
  dependencies:
  - name: CAAPM
    version: 10.7.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: appdynamics
    version: 4.5.12.2925
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: composer
    version: 1.9.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: httpd
    version: 2.4.39
    cf_stacks:
    - cflinuxfs2
  - name: httpd
    version: 2.4.39
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 8.1.0.209
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: nginx
    version: 1.15.12
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.15.12
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.16.0
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.16.0
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.2
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.17.2
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.30
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.1.30
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.31
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.1.31
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.20
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.2.20
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.21
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.2.21
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.7
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.8
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.6.36
  sha: 3628a429f7b3c357e1acdbe2cc620c0c15a8463e68e762f4443c0ed7a39356e8
  filename: python-buildpack-cflinuxfs3-v1.6.36.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.36/python-buildpack-cflinuxfs3-v1.6.36.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: miniconda2
    version: 4.6.14
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: miniconda3
    version: 4.6.14
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs2
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.15
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 2.7.15
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.16
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 2.7.16
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.4.9
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.4.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.4.10
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.4.10
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.6
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.5.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.5.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.8
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.6.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.9
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.6.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.3
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.4
    cf_stacks:
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.7.42
  sha: ad1e736567f7415ac62f208cbc61972089499acc80112c20b12286503477bab9
  filename: ruby-buildpack-cflinuxfs3-v1.7.42.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.42/ruby-buildpack-cflinuxfs3-v1.7.42.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: bundler
    version: 2.0.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs2
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.7.0
    cf_stacks:
    - cflinuxfs2
  - name: jruby
    version: 9.2.7.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.15.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.16.0
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: ruby
    version: 2.4.5
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.4.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.6
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.4.6
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.3
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.5.3
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.5
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.5.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.2
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.6.2
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.3
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.6.3
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.0.4
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: yarn
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.4.44
  sha: b859805d2b7bb9cd115b6e5891ed716906a7aad212125f6688fd94b8126b55df
  filename: staticfile-buildpack-cflinuxfs3-v1.4.44.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.4.44/staticfile-buildpack-cflinuxfs3-v1.4.44.zip
  dependencies:
  - name: nginx
    version: 1.15.12
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.15.12
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.0.17
  sha: 6fa9f995f103c6a42e9c131f514f000fd5563a2a525f1867253785b5706ce690
  filename: nginx-buildpack-cflinuxfs3-v1.0.17.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.0.17/nginx-buildpack-cflinuxfs3-v1.0.17.zip
  dependencies:
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.16.1
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.17.3
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs2
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs3
  - name: openresty
    version: 1.15.8.1
    cf_stacks:
    - cflinuxfs2
  - name: openresty
    version: 1.15.8.1
    cf_stacks:
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.0.12
  sha: 09b08068fe34a0c5767aaf1b218c2ad7b07f1c4c5166da70e947fc3641ad610f
  filename: r-buildpack-cflinuxfs3-v1.0.12.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.0.12/r-buildpack-cflinuxfs3-v1.0.12.zip
  dependencies:
  - name: r
    version: 3.4.3
    cf_stacks:
    - cflinuxfs2
  - name: r
    version: 3.4.4
    cf_stacks:
    - cflinuxfs2
  - name: r
    version: 3.4.4
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs2
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs2
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.0
    cf_stacks:
    - cflinuxfs3
  - name: r
    version: 3.6.1
    cf_stacks:
    - cflinuxfs3
