buildpacks:
- name: binary_buildpack
  repo_name: binary-buildpack
  stack: cflinuxfs3
  version: v1.0.31
  sha: 5a869d5c256932f5288c42755b8e65d7e9731f0ff2226c244cb3cd13bebd34a1
  filename: binary-buildpack-cflinuxfs3-v1.0.31.zip
  url: https://github.com/cloudfoundry/binary-buildpack/releases/download/v1.0.31/binary-buildpack-cflinuxfs3-v1.0.31.zip
  dependencies: []
- name: dotnet_core_buildpack
  repo_name: dotnet-core-buildpack
  stack: cflinuxfs3
  version: v2.2.8
  sha: 9d4d330060ae1afb4c96ba0d1c567f5940f706854c7d22fe4a689f2a75859100
  filename: dotnet-core-buildpack-cflinuxfs3-v2.2.8.zip
  url: https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v2.2.8/dotnet-core-buildpack-cflinuxfs3-v2.2.8.zip
  dependencies:
  - name: bower
    version: 1.8.8
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.7
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.7
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.8
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.1.9
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.1.9
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.2.2
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.2.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-aspnetcore
    version: 2.2.3
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-aspnetcore
    version: 2.2.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 1.0.11
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.0.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.11
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 1.1.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 1.1.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.7
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.7
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.8
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.8
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.1.9
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.1.9
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.2.1
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.2.1
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.2.2
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.2.2
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-runtime
    version: 2.2.3
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-runtime
    version: 2.2.3
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 1.1.11
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.11
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 1.1.12
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.12
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 1.1.13
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 1.1.13
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.403
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.1.403
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.1.505
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.1.505
    cf_stacks:
    - cflinuxfs3
  - name: dotnet-sdk
    version: 2.2.105
    cf_stacks:
    - cflinuxfs2
  - name: dotnet-sdk
    version: 2.2.105
    cf_stacks:
    - cflinuxfs3
  - name: libgdiplus
    version: "5.6"
    cf_stacks:
    - cflinuxfs2
  - name: libgdiplus
    version: "5.6"
    cf_stacks:
    - cflinuxfs3
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs2
  - name: libunwind
    version: 1.3.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs3
- name: go_buildpack
  repo_name: go-buildpack
  stack: cflinuxfs3
  version: v1.8.36
  sha: 3e22f3a3274c0dc1e8ecff4bb01922e370435214d1b04440efba720f5ae12576
  filename: go-buildpack-cflinuxfs3-v1.8.36.zip
  url: https://github.com/cloudfoundry/go-buildpack/releases/download/v1.8.36/go-buildpack-cflinuxfs3-v1.8.36.zip
  dependencies:
  - name: dep
    version: 0.5.1
    cf_stacks:
    - cflinuxfs2
  - name: dep
    version: 0.5.1
    cf_stacks:
    - cflinuxfs3
  - name: glide
    version: 0.13.2
    cf_stacks:
    - cflinuxfs2
  - name: glide
    version: 0.13.2
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.10.7
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.10.7
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.10.8
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.10.8
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.11.5
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.11.5
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.11.6
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.11.6
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: "1.12"
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: "1.12"
    cf_stacks:
    - cflinuxfs3
  - name: go
    version: 1.12.1
    cf_stacks:
    - cflinuxfs2
  - name: go
    version: 1.12.1
    cf_stacks:
    - cflinuxfs3
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs2
  - name: godep
    version: "80"
    cf_stacks:
    - cflinuxfs3
- name: java_buildpack
  repo_name: java-buildpack
  stack: cflinuxfs3
  version: v4.18
  sha: 61bbd5792d0629d604aeff4aa409c44b85716ac69fa8fc4263b934b75fdd249b
  filename: java-buildpack-v4.18.zip
  url: https://github.com/cloudfoundry/java-buildpack/releases/download/v4.18/java-buildpack-v4.18.zip
  dependencies: []
- name: nodejs_buildpack
  repo_name: nodejs-buildpack
  stack: cflinuxfs3
  version: v1.6.46
  sha: 7d7826abc5a52c16a3f85aa1e789d2b2a5dfb1fa26b3a95ebfba9c5f6e7a3362
  filename: nodejs-buildpack-cflinuxfs3-v1.6.46.zip
  url: https://github.com/cloudfoundry/nodejs-buildpack/releases/download/v1.6.46/nodejs-buildpack-cflinuxfs3-v1.6.46.zip
  dependencies:
  - name: node
    version: 6.16.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 6.16.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 8.15.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 8.15.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 8.15.1
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 8.15.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.14.2
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.15.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 10.15.2
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 10.15.3
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 11.10.1
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 11.12.0
    cf_stacks:
    - cflinuxfs3
  - name: yarn
    version: 1.15.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: php_buildpack
  repo_name: php-buildpack
  stack: cflinuxfs3
  version: v4.3.72
  sha: d21bfbdbcd992c7a19270ca4ea559db4491bc7f6db7b8efa21c1c9583cc36e11
  filename: php-buildpack-cflinuxfs3-v4.3.72.zip
  url: https://github.com/cloudfoundry/php-buildpack/releases/download/v4.3.72/php-buildpack-cflinuxfs3-v4.3.72.zip
  dependencies:
  - name: CAAPM
    version: 10.7.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: appdynamics
    version: 4.5.7.2661
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: composer
    version: 1.8.4
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: httpd
    version: 2.4.38
    cf_stacks:
    - cflinuxfs2
  - name: httpd
    version: 2.4.38
    cf_stacks:
    - cflinuxfs3
  - name: newrelic
    version: 8.1.0.209
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: nginx
    version: 1.14.2
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.14.2
    cf_stacks:
    - cflinuxfs3
  - name: nginx
    version: 1.15.9
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.15.9
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.26
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.1.26
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.1.27
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.1.27
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.15
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.2.15
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.2.16
    cf_stacks:
    - cflinuxfs2
  - name: php
    version: 7.2.16
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.2
    cf_stacks:
    - cflinuxfs3
  - name: php
    version: 7.3.3
    cf_stacks:
    - cflinuxfs3
- name: python_buildpack
  repo_name: python-buildpack
  stack: cflinuxfs3
  version: v1.6.29
  sha: 704a7e137bb66c45e50e74b0a39dd7ae92bb9cd813668d03d838f5c762919fc6
  filename: python-buildpack-cflinuxfs3-v1.6.29.zip
  url: https://github.com/cloudfoundry/python-buildpack/releases/download/v1.6.29/python-buildpack-cflinuxfs3-v1.6.29.zip
  dependencies:
  - name: libffi
    version: 3.2.1
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: libmemcache
    version: 1.0.18
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: miniconda2
    version: 4.5.12
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: miniconda3
    version: 4.5.12
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: pip
    version: 9.0.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: pip-pop
    version: 0.1.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs2
  - name: pipenv
    version: 2018.11.26
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.15
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 2.7.15
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 2.7.16
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 2.7.16
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.4.8
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.4.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.4.9
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.4.9
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.5
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.5.5
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.5.6
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.5.6
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.7
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.6.7
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.6.8
    cf_stacks:
    - cflinuxfs2
  - name: python
    version: 3.6.8
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.1
    cf_stacks:
    - cflinuxfs3
  - name: python
    version: 3.7.2
    cf_stacks:
    - cflinuxfs3
  - name: setuptools
    version: 40.8.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: ruby_buildpack
  repo_name: ruby-buildpack
  stack: cflinuxfs3
  version: v1.7.35
  sha: aa82ee8192989150ec2a85482f649b9ae34361d6e76e76c9000ed02a2f77a84f
  filename: ruby-buildpack-cflinuxfs3-v1.7.35.zip
  url: https://github.com/cloudfoundry/ruby-buildpack/releases/download/v1.7.35/ruby-buildpack-cflinuxfs3-v1.7.35.zip
  dependencies:
  - name: bundler
    version: 1.17.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: bundler
    version: 2.0.1
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs2
  - name: jruby
    version: 9.1.17.0
    cf_stacks:
    - cflinuxfs3
  - name: jruby
    version: 9.2.6.0
    cf_stacks:
    - cflinuxfs2
  - name: jruby
    version: 9.2.6.0
    cf_stacks:
    - cflinuxfs3
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs2
  - name: node
    version: 6.17.0
    cf_stacks:
    - cflinuxfs3
  - name: openjdk1.8-latest
    version: 1.8.0
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: ruby
    version: 2.2.9
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.2.10
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.2.10
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.3.7
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.3.7
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.3.8
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.3.8
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.4
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.4.4
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.4.5
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.4.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.3
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.5.3
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.5.5
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.5.5
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.1
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.6.1
    cf_stacks:
    - cflinuxfs3
  - name: ruby
    version: 2.6.2
    cf_stacks:
    - cflinuxfs2
  - name: ruby
    version: 2.6.2
    cf_stacks:
    - cflinuxfs3
  - name: rubygems
    version: 3.0.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: yarn
    version: 1.15.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: staticfile_buildpack
  repo_name: staticfile-buildpack
  stack: cflinuxfs3
  version: v1.4.40
  sha: 1a2e160fbb596be0b539c0c0eb92d0ed9ef6494c9875e45855f019c4c7d19270
  filename: staticfile-buildpack-cflinuxfs3-v1.4.40.zip
  url: https://github.com/cloudfoundry/staticfile-buildpack/releases/download/v1.4.40/staticfile-buildpack-cflinuxfs3-v1.4.40.zip
  dependencies:
  - name: nginx
    version: 1.15.9
    cf_stacks:
    - cflinuxfs2
  - name: nginx
    version: 1.15.9
    cf_stacks:
    - cflinuxfs3
- name: nginx_buildpack
  repo_name: nginx-buildpack
  stack: cflinuxfs3
  version: v1.0.8
  sha: 18b5f7ee6b63b7c6463ef97b5706f4db0c260bc7efc7024f1508930b7be69bf9
  filename: nginx-buildpack-cflinuxfs3-v1.0.8.zip
  url: https://github.com/cloudfoundry/nginx-buildpack/releases/download/v1.0.8/nginx-buildpack-cflinuxfs3-v1.0.8.zip
  dependencies:
  - name: nginx
    version: 1.14.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: nginx
    version: 1.15.8
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: openresty
    version: 1.13.6.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
- name: r_buildpack
  repo_name: r-buildpack
  stack: cflinuxfs3
  version: v1.0.8
  sha: e1717a96610edec81e5d3fdddf08e1404697333cbc8e9aee439c6bb4a3b45403
  filename: r-buildpack-cflinuxfs3-v1.0.8.zip
  url: https://github.com/cloudfoundry/r-buildpack/releases/download/v1.0.8/r-buildpack-cflinuxfs3-v1.0.8.zip
  dependencies:
  - name: r
    version: 3.4.3
    cf_stacks:
    - cflinuxfs2
  - name: r
    version: 3.4.4
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: r
    version: 3.5.2
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
  - name: r
    version: 3.5.3
    cf_stacks:
    - cflinuxfs2
    - cflinuxfs3
