- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/app_ssh/host_key_fingerprint
  value: ((secrets_ssh_proxy_host_key.public_fingerprint))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/bulk_api_password
  value: ((secrets_bulk_api_password))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/db_encryption_key
  value: ((secrets_cc_db_encryption_key))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/internal_api_password
  value: ((secrets_bulk_api_password))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/staging_upload_password
  value: ((secrets_staging_upload_password))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/router/route_services_secret
  value: ((secrets_route_services_secret))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/uaa/clients/cc-service-dashboards/secret
  value: ((secrets_uaa_clients_cc_service_dashboards_password))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/uaa/clients/cc_routing/secret
  value: ((secrets_uaa_cc_routing_secret))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/uaa/clients/cc_service_key_client/secret
  value: ((secrets_uaa_clients_cc_service_key_client_secret))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/uaa/clients/cloud_controller_username_lookup/secret
  value: ((secrets_uaa_clients_cloud_controller_username_lookup_secret))
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/cf_networking/policy_server/database/password
  value: ((secrets_cf_db_network_policy_password))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/db_encryption_key
  value: ((secrets_cc_db_encryption_key))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/internal_api_password
  value: ((secrets_bulk_api_password))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/staging_upload_password
  value: ((secrets_staging_upload_password))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/uaa/clients/cc-service-dashboards/secret
  value: ((secrets_uaa_clients_cc_service_dashboards_password))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/uaa/clients/cc_routing/secret
  value: ((secrets_uaa_cc_routing_secret))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/encryption_keys/0/passphrase
  value: ((secrets_bbs_encryption_key))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_password
  value: ((secrets_cf_db_bbs_password))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/password
  value: ((secrets_cf_db_network_connectivity_password))
- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/loggregator/uaa/client_secret
  value: ((secrets_uaa_clients_doppler_secret))
- type: replace
  path: /instance_groups/name=nats/jobs/name=nats/properties/nats/password
  value: ((secrets_nats_password))
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/route_services_secret
  value: ((secrets_route_services_secret))
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/router/status/password
  value: ((secrets_router_password))
- type: replace
  path: /instance_groups/name=router/jobs/name=gorouter/properties/uaa/clients/gorouter/secret
  value: ((secrets_uaa_clients_gorouter_secret))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/db_encryption_key
  value: ((secrets_cc_db_encryption_key))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/internal_api_password
  value: ((secrets_bulk_api_password))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/staging_upload_password
  value: ((secrets_staging_upload_password))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/uaa/clients/cc-service-dashboards/secret
  value: ((secrets_uaa_clients_cc_service_dashboards_password))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/uaa/clients/cc_routing/secret
  value: ((secrets_uaa_cc_routing_secret))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/host_key
  value: ((secrets_ssh_proxy_host_key.private_key))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=ssh_proxy/properties/diego/ssh_proxy/uaa_secret
  value: ((secrets_uaa_clients_ssh_proxy_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/admin/client_secret
  value: ((secrets_uaa_admin_client_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cc-service-dashboards/secret
  value: ((secrets_uaa_clients_cc_service_dashboards_password))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cc_routing/secret
  value: ((secrets_uaa_cc_routing_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cc_service_key_client/secret
  value: ((secrets_uaa_clients_cc_service_key_client_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/cloud_controller_username_lookup/secret
  value: ((secrets_uaa_clients_cloud_controller_username_lookup_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/doppler/secret
  value: ((secrets_uaa_clients_doppler_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/gorouter/secret
  value: ((secrets_uaa_clients_gorouter_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/clients/ssh-proxy/secret
  value: ((secrets_uaa_clients_ssh_proxy_secret))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaa/scim/users/name=admin/password
  value: ((secrets_uaa_admin_password))
