- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/buildpacks/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/droplets/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/packages/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/resource_pool/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/ccdb/address
  value: ((terraform_outputs_cf_db_address))
- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))
- type: replace
  path: /instance_groups/name=api/jobs/name=policy-server/properties/cf_networking/policy_server/database/host
  value: ((terraform_outputs_cf_db_address))
- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/host
  value: ((terraform_outputs_cf_db_address))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/buildpacks/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/droplets/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/packages/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/cc/resource_pool/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/ccdb/address
  value: ((terraform_outputs_cf_db_address))
- type: replace
  path: /instance_groups/name=cc-worker/jobs/name=cloud_controller_worker/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))
- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/buildpacks/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/droplets/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/packages/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/cc/resource_pool/fog_connection/region
  value: ((terraform_outputs_region))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/ccdb/address
  value: ((terraform_outputs_cf_db_address))
- type: replace
  path: /instance_groups/name=scheduler/jobs/name=cloud_controller_clock/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))
- type: replace
  path: /instance_groups/name=uaa/jobs/name=uaa/properties/uaadb/address
  value: ((terraform_outputs_cf_db_address))
