---

- type: replace
  path: /instance_groups/name=diego-api/vm_extensions?/-
  value:
    cf_rds_client_sg

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/require_ssl?
  value: true

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/active_key_label
  value: key-2017-01

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/auctioneer/require_tls?
  value: true

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/encryption_keys/0/label
  value: key-2017-01

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_host
  value: ((terraform_outputs_cf_db_address))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_password
  value: ((external_bbs_database_password))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_schema
  value: bbs

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=bbs/properties/diego/bbs/sql/db_username
  value: bbs

- type: remove
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/consumes

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/host
  value: ((terraform_outputs_cf_db_address))

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/name
  value: network_connectivity

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/username
  value: network_connectivity

- type: replace
  path: /instance_groups/name=diego-api/jobs/name=silk-controller/properties/cf_networking/silk_controller/database/password
  value: ((external_network_connectivity_database_password))

- type: remove
  path: /variables/name=diego_instance_identity_ca
