---
- type: replace
  path: /instance_groups/name=log-api/vm_extensions?/-
  value: cf_loggregator_doppler_target_groups
  
- type: remove
  path: /instance_groups/name=log-api/jobs/name=route_registrar

- type: replace
  path: /instance_groups/name=log-api/jobs/name=loggregator_trafficcontroller/properties/system_domain
  value: ((terraform_outputs_cf_root_domain))

- type: replace
  path: /instance_groups/name=log-api/azs/-
  value: z3

- type: replace
  path: /instance_groups/name=log-api/instances
  value: ((log_api_instances))

- type: replace
  path: /releases/name=loggregator
  value:
    name: "loggregator"
    version: "105.6"
    url: "https://bosh.io/d/github.com/cloudfoundry/loggregator-release?v=105.6"
    sha1: "eccfbd65e1d217a2b46afd414163e82553fb3084"

