---

- type: replace
  path: /releases/-
  value:
    name: datadog-for-cloudfoundry
    version: 0.1.26
    url: https://s3-eu-west-1.amazonaws.com/gds-paas-build-releases/datadog-for-cloudfoundry-0.1.26.tgz
    sha1: c47959e19137a2f6420422baa6f8b1f1abe25879


- type: replace
  path: /instance_groups/name=consul/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=consul/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=consul/jobs/-
  value:
    name: datadog-consul-agent-server
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: datadog-cc
    properties:
      cc:
        external_port: 9022
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=cc-worker/jobs/-
  value:
    name: datadog-cc-worker
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=cc-worker/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=cc-worker/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    name: datadog-bbs
    release: datadog-for-cloudfoundry
    properties:
      bbs:
        url: "https://bbs.service.cf.internal:8889/v1/actual_lrp_groups/list"
        client_cert: "/var/vcap/jobs/cfdot/config/certs/cfdot/client.crt"
        client_key: "/var/vcap/jobs/cfdot/config/certs/cfdot/client.key"
        ca_cert: "/var/vcap/jobs/cfdot/config/certs/cfdot/ca.crt"

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-api/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-garden
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-ipsec
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-rep
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: datadog-route-emitter
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=doppler/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=log-api/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=log-api/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=nats/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=nats/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=nats/jobs/-
  value:
    name: datadog-nats
    release: datadog-for-cloudfoundry
    consumes:
      nats:
        from: nats

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: datadog-ipsec
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: datadog-router
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=uaa/jobs/-
  value:
    name: datadog-bosh-dns
    release: datadog-for-cloudfoundry

- type: replace
  path: /instance_groups/name=uaa/jobs/-
  value:
    name: datadog-consul-agent-client
    release: datadog-for-cloudfoundry
