---

- type: replace
  path: /releases/-
  value:
    name: ipsec
    version: "3"
    url: "https://bosh.io/d/github.com/SAP/ipsec-release?v=3"
    sha1: "382e16ecbb5f38d378fc36de061c515b66d9a8ca"

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: racoon
    release: ipsec
    properties:
      racoon:
        ports:
        - name: router
          targets: ((terraform_outputs_cell_subnet_cidr_blocks))
        certificate_authority_private_key: "((ipsec_ca.private_key))"
        certificate_authority_cert: "((ipsec_ca.certificate))"
        level: use
        verify_certificate: 'on'

- type: replace
  path: /instance_groups/name=diego-cell/jobs/-
  value:
    name: racoon
    release: ipsec
    properties:
      racoon:
        ports:
        - name: cell
          targets: ((terraform_outputs_router_subnet_cidr_blocks))
        certificate_authority_private_key: "((ipsec_ca.private_key))"
        certificate_authority_cert: "((ipsec_ca.certificate))"
        level: use
        verify_certificate: 'on'
