
- type: replace
  path: /instance_groups/name=api/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=cc-worker/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=diego-api/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=doppler/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=log-api/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=nats/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=scheduler/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=uaa/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=rotate-cc-database-key/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=router/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=diego-cell/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=rds_broker/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=cdn_broker/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=elasticache_broker/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=s3_broker/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=prometheus/env?/bosh/password
  value: ((vcap_password))
- type: replace
  path: /instance_groups/name=vault/env?/bosh/password
  value: ((vcap_password))
