disk_pools:
  - name: graphite_data
    disk_size: 204800
    cloud_properties: {type: gp2}

resource_pools:
  - name: graphite_z1
    network: cf1
    stemcell: (( grab meta.stemcell ))
    env: (( grab meta.default_env ))
    cloud_properties:
      instance_type: m3.large
      ephemeral_disk:
        size: 65_536
        type: gp2
      availability_zone: (( grab meta.zones.z1 ))
      elbs:
        - (( grab terraform_outputs.metrics_elb_name ))

jobs:
  - name: graphite_z1
    persistent_disk_pool: graphite_data
    networks:
    - name: cf1
      static_ips: (( static_ips(10) ))
