# The following line helps maintain current documentation at http://docs.cloudfoundry.org.
# code_snippet cf-stub-aws start
---
meta:
  environment: (( grab terraform_outputs.environment ))
  default_env:
    bosh:
      password: (( grab secrets.vcap_password ))

director_uuid: ~

networks:
- name: cf1
  subnets:
    - range: 10.0.16.0/24
      reserved:
        - 10.0.16.2 - 10.0.16.9
        - 10.0.16.41 - 10.0.16.50
      static:
        - 10.0.16.10 - 10.0.16.40
      dynamic:
        - 10.0.16.51 - 10.0.16.255
      gateway: 10.0.16.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf1_subnet_id ))

- name: cf1_rds
  subnets:
    - range: 10.0.16.0/24
      reserved:
        - 10.0.16.2 - 10.0.16.9
        - 10.0.16.10 - 10.0.16.40
        - 10.0.16.51 - 10.0.16.255
      static: []
      dynamic:
        - 10.0.16.41 - 10.0.16.50
      gateway: 10.0.16.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf1_subnet_id ))
        security_groups:
          - (( grab terraform_outputs.default_security_group ))
          - (( grab terraform_outputs.cf_rds_client_security_group ))

- name: cf2
  subnets:
    - range: 10.0.17.0/24
      reserved:
        - 10.0.17.2 - 10.0.17.9
        - 10.0.17.41 - 10.0.17.50
      static:
        - 10.0.17.10 - 10.0.17.40
      dynamic:
        - 10.0.17.51 - 10.0.17.255
      gateway: 10.0.17.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf2_subnet_id ))

- name: cf2_rds
  subnets:
    - range: 10.0.17.0/24
      reserved:
        - 10.0.17.2 - 10.0.17.9
        - 10.0.17.10 - 10.0.17.40
        - 10.0.17.51 - 10.0.17.255
      static: []
      dynamic:
        - 10.0.17.41 - 10.0.17.50
      gateway: 10.0.17.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf2_subnet_id ))
        security_groups:
          - (( grab terraform_outputs.default_security_group ))
          - (( grab terraform_outputs.cf_rds_client_security_group ))

- name: cf3
  subnets:
    - range: 10.0.18.0/24
      reserved:
        - 10.0.18.2 - 10.0.18.9
      static:
        - 10.0.18.10 - 10.0.18.40
      dynamic:
        - 10.0.18.51 - 10.0.18.255
      gateway: 10.0.18.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf3_subnet_id ))

- name: cf3_rds
  subnets:
    - range: 10.0.18.0/24
      reserved:
        - 10.0.18.2 - 10.0.18.9
        - 10.0.18.10 - 10.0.18.40
        - 10.0.18.51 - 10.0.18.255
      static: []
      dynamic:
        - 10.0.18.41 - 10.0.18.50
      gateway: 10.0.18.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cf3_subnet_id ))
        security_groups:
          - (( grab terraform_outputs.default_security_group ))
          - (( grab terraform_outputs.cf_rds_client_security_group ))

- name: cell1
  subnets:
    - range: 10.0.32.0/24
      reserved:
        - 10.0.32.2 - 10.0.32.3
      gateway: 10.0.32.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cell1_subnet_id ))
- name: cell2
  subnets:
    - range: 10.0.33.0/24
      reserved:
        - 10.0.33.2 - 10.0.33.3
      gateway: 10.0.33.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.cell2_subnet_id ))

- name: router1
  subnets:
    - range: 10.0.48.0/24
      reserved:
        - 10.0.48.2 - 10.0.48.3
      static:
        - 10.0.48.4 - 10.0.48.100
      gateway: 10.0.48.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.router1_subnet_id ))
- name: router2
  subnets:
    - range: 10.0.49.0/24
      reserved:
        - 10.0.49.2 - 10.0.49.3
      static:
        - 10.0.49.4 - 10.0.49.100
      gateway: 10.0.49.1
      dns:
        - 10.0.0.2
      cloud_properties:
        subnet: (( grab terraform_outputs.router2_subnet_id ))


properties:
  domain: (( grab terraform_outputs.cf_root_domain ))
  system_domain: (( grab terraform_outputs.cf_root_domain ))
  system_domain_organization: GDS
  app_domains:
   - (( grab terraform_outputs.cf_apps_domain ))
  cc:
    staging_upload_user: staging_upload_user
    staging_upload_password: (( grab secrets.staging_upload_password ))
    bulk_api_password: (( grab secrets.bulk_api_password ))
    db_encryption_key: (( grab secrets.cc_db_encryption_key ))
  consul:
    encrypt_keys: (( grab secrets.consul_encrypt_keys ))
    ca_cert: (( grab meta.secrets.consul_ca_cert ))
    server_cert: (( grab secrets.consul_server_cert ))
    server_key: (( grab secrets.consul_server_key ))
    agent_cert: (( grab secrets.consul_agent_cert ))
    agent_key: (( grab secrets.consul_agent_key ))
    agent:
      domain: cf.internal
  loggregator_endpoint:
    shared_secret: (( grab secrets.loggregator_endpoint_shared_secret ))
  nats:
    user: nats_user
    password: (( grab secrets.nats_password ))
  router:
    status:
      user: router_user
      password: (( grab secrets.router_password ))
  uaa:
    admin:
      client_secret: (( grab secrets.uaa_admin_client_secret ))
    cc:
      client_secret: (( grab secrets.uaa_cc_client_secret ))
    clients:
      cc_routing:
        secret: (( grab secrets.uaa_cc_routing_secret ))
      cloud_controller_username_lookup:
        secret: (( grab secrets.uaa_clients_cloud_controller_username_lookup_secret ))
      doppler:
        secret: (( grab secrets.uaa_clients_doppler_secret ))
      gorouter:
        secret: (( grab secrets.uaa_clients_gorouter_secret ))
      login:
        secret: (( grab secrets.uaa_clients_login_secret ))
      notifications:
        secret: (( grab secrets.uaa_clients_notifications_secret ))

    jwt:
      verification_key: (( grab secrets.uaa_jwt_verification_key ))
      signing_key: (( grab secrets.uaa_jwt_signing_key ))
    scim:
      users:
        - (( concat "admin|" secrets.uaa_admin_password "|scim.write,scim.read,openid,cloud_controller.admin,doppler.firehose" ))

  ccdb:
    db_scheme: postgres
    address: (( grab terraform_outputs.cf_db_address ))
    port: 5432
    roles:
      - tag: admin
        name: api
        password: (( grab secrets.cf_db_api_password ))
    databases:
      - tag: cc
        name: api
        citext: true

  uaadb:
    db_scheme: postgresql
    address: (( grab terraform_outputs.cf_db_address ))
    port: 5432
    roles:
      - tag: admin
        name: uaa
        password: (( grab secrets.cf_db_uaa_password ))
    databases:
      - tag: uaa
        name: uaa
        citext: true

# code_snippet cf-stub-aws end
# The previous line helps maintain current documentation at http://docs.cloudfoundry.org.
