cloud_provider:
  mbus: https://mbus:BOSH_NATS_PASSWORD@bosh.example.com:6868
  properties:
    agent:
      mbus: https://mbus:BOSH_NATS_PASSWORD@0.0.0.0:6868
    aws:
      credentials_source: env_or_profile
      default_key_name: ssh_key_pair
      default_security_groups:
      - bosh_default_sg
      region: eu-west-1
    blobstore:
      path: /var/vcap/micro_bosh/data/cache
      provider: local
    ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
  ssh_tunnel:
    host: bosh.example.com
    port: 22
    private_key: .ssh/id_rsa
    user: vcap
  template:
    name: aws_cpi
    release: bosh-aws-cpi
disk_pools:
- cloud_properties:
    type: gp2
  disk_size: 32768
  name: disks
jobs:
- instances: 1
  name: bosh
  networks:
  - default:
    - dns
    - gateway
    name: private
    static_ips:
    - 10.0.0.6
  - name: public
    static_ips:
    - 194.1.2.4
  persistent_disk_pool: disks
  properties:
    agent:
      mbus: nats://nats:BOSH_NATS_PASSWORD@bosh.example.com:4222
    aws:
      credentials_source: env_or_profile
      default_iam_instance_profile: bosh-managed
      default_key_name: ssh_key_pair
      default_security_groups:
      - bosh_default_sg
      region: eu-west-1
    blobstore:
      bucket_name: test-bosh-blobstore
      credentials_source: env_or_profile
      provider: s3
      s3_region: eu-west-1
    compiled_package_cache:
      options:
        bucket_name: shared-cf-bosh-blobstore-unit-test
        credentials_source: env_or_profile
        host: s3-eu-west-1.amazonaws.com
      provider: s3
    director:
      address: 127.0.0.1
      cpi_job: aws_cpi
      db:
        adapter: postgres
        database: bosh
        host: 1.2.3.4
        password: BOSH_POSTGRES_PASSWORD
        port: 5432
        user: bosh
      disks:
        max_orphaned_age_in_days: 0
      ignore_missing_gateway: "false"
      name: my-bosh
      user_management:
        local:
          users:
          - name: admin
            password: BOSH_ADMIN_PASSWORD
        provider: local
    dns: null
    hm:
      director_account:
        password: BOSH_HM_DIRECTOR_PASSWORD
        user: admin
      resurrector_enabled: true
    nats:
      address: 127.0.0.1
      password: BOSH_NATS_PASSWORD
      user: nats
    ntp:
    - 0.pool.ntp.org
    - 1.pool.ntp.org
    postgres:
      adapter: postgres
      database: bosh
      host: 1.2.3.4
      password: BOSH_POSTGRES_PASSWORD
      port: 5432
      user: bosh
    redis:
      address: 127.0.0.1
      listen_address: 127.0.0.1
      password: BOSH_REDIS_PASSWORD
    registry:
      db:
        adapter: postgres
        database: bosh
        host: 1.2.3.4
        password: BOSH_POSTGRES_PASSWORD
        port: 5432
        user: bosh
      host: bosh.example.com
      http:
        password: BOSH_REGISTRY_PASSWORD
        user: admin
      password: BOSH_REGISTRY_PASSWORD
      username: admin
  resource_pool: vms
  templates:
  - name: nats
    release: bosh
  - name: redis
    release: bosh
  - name: director
    release: bosh
  - name: health_monitor
    release: bosh
  - name: collectd
    release: collectd
  - name: registry
    release: bosh
  - name: aws_cpi
    release: bosh-aws-cpi
name: bosh
networks:
- name: private
  subnets:
  - cloud_properties:
      security_groups:
      - bosh_security_group
      subnet: subnet-bosh
    dns:
    - 10.0.0.2
    gateway: 10.0.0.1
    range: 10.0.0.0/24
  type: manual
- name: public
  type: vip
properties:
  collectd:
    config: |
      WriteQueueLimitHigh 100000
      LoadPlugin cpu
      LoadPlugin disk
      LoadPlugin entropy
      LoadPlugin interface
      LoadPlugin load
      LoadPlugin memory
      LoadPlugin swap
      LoadPlugin uptime

      LoadPlugin df
      <Plugin df>
        ReportInodes true
        ReportReserved true
      </Plugin>

      LoadPlugin syslog
      <Plugin syslog>
        LogLevel warning
        NotifyLevel WARNING
      </Plugin>

      LoadPlugin vmem
      <Plugin vmem>
        Verbose false
      </Plugin>

      LoadPlugin "write_graphite"
      <Plugin "write_graphite">
       <Node "myNode">
         #FIXME: hard coded static IP to be removed during #121602315
         # This address comes from 040-graphite.yml:31 in the CloudFoundry
         # manifest and has been copied as `grab` cannot interpolate in a
         # multi-line string.
         Host "10.0.16.20"
         Port "2003"
         Prefix "collectd."
         EscapeCharacter "_"
         SeparateInstances true
         StoreRates false
         AlwaysAppendDS false
       </Node>
      </Plugin>
    hostname_prefix: bosh_
    interval: 10
  director:
    trusted_certs: |
      -----BEGIN RSA PRIVATE KEY-----
      BOS_CA_000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      0000000000000000000000000000000000000000000000000000000000000000
      -----END RSA PRIVATE KEY-----

releases:
- name: bosh
  sha1: 6b12652650b87810dcef1be1f6a6d23f1c0c13a7
  url: https://bosh.io/d/github.com/cloudfoundry/bosh?v=255.8
- name: collectd
  sha1: 89d9afbb4e682f31e745f07bd40ff569d347343f
  url: https://github.com/alphagov/paas-collectd-boshrelease/releases/download/0.4/collectd-0.4.tgz
- name: bosh-aws-cpi
  sha1: dc4a0cca3b33dce291e4fbeb9e9948b6a7be3324
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=52
resource_pools:
- cloud_properties:
    availability_zone: eu-west-1a
    ephemeral_disk:
      size: 40000
      type: gp2
    iam_instance_profile: bosh-director
    instance_type: t2.medium
  env:
    bosh:
      password: BOSH_VCAP_PASSWORD
  name: vms
  network: private
  stemcell:
    sha1: ac920cae17c7159dee3bf1ebac727ce2d01564e9
    url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3232.4
