---

# AWS Limits not accesible via API
aws_limits_elasticache_cache_parameter_groups: 20
aws_limits_elasticache_nodes: 100
aws_limits_s3_buckets: 150
aws_limits_rds_instances: 40
prometheus_disk_size: 100GB
