---
meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))

releases:
  - name: concourse
    url: https://bosh.io/d/github.com/concourse/concourse?v=2.2.1
    sha1: 879d5cb45d12f173ff4c7912c7c7cdcd3e18c442
  - name: garden-runc
    url: https://bosh.io/d/github.com/cloudfoundry/garden-runc-release?v=0.8.0
    sha1: 20e98ea84c8f4426bba00bbca17d931e27d3c07d
  # When updating the version of the CPI here, the version used in the
  # bosh-init container must also be updated so that the cached CPI compile
  # will be used.
  - name: bosh-aws-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-aws-cpi-release?v=52
    sha1: dc4a0cca3b33dce291e4fbeb9e9948b6a7be3324

resource_pools:
  - name: concourse
    network: concourse
    stemcell:
      url: https://bosh.io/d/stemcells/bosh-aws-xen-hvm-ubuntu-trusty-go_agent?v=3263.5
      sha1: a4a3b387ee81cd0e1b73debffc39f0907b80f9c6
    cloud_properties:
      instance_type: m4.large
      availability_zone: (( grab terraform_outputs.zone0 ))
      iam_instance_profile: deployer-concourse
      elbs:
      - (( grab terraform_outputs.concourse_elb_name ))
      ephemeral_disk:
        size: 102400
        type: gp2
    env:
      bosh:
        password: (( grab secrets.concourse_vcap_password ))

disk_pools:
  - name: db
    disk_size: 10240
    cloud_properties:
      type: gp2

networks:
  - name: concourse
    type: manual
    subnets:
      - range: 10.0.0.0/24
        dns: [10.0.0.2]
        gateway: 10.0.0.1
        reserved:
        - 10.0.0.0 - 10.0.0.9
        static:
        - 10.0.0.10 - 10.0.0.20

        cloud_properties:
          subnet: (( grab terraform_outputs.subnet0_id ))
  - name: public
    type: vip

jobs:
  - name: concourse
    instances: 1
    resource_pool: concourse
    persistent_disk_pool: db

    templates:
      - name: postgresql
        release: concourse
        properties:
          databases:
            - name: atc
              role: atc
              password: (( grab secrets.concourse_postgres_password ))

      - name: atc
        release: concourse
        properties:
          external_url: (( concat "https://" terraform_outputs.concourse_dns_name ))
          basic_auth_username: admin
          basic_auth_password: (( grab secrets.concourse_atc_password ))

          postgresql:
            address: 127.0.0.1:5432
            database: atc
            role:
              name: atc
              password: (( grab secrets.concourse_postgres_password ))

      - name: groundcrew
        release: concourse
        properties:
          baggageclaim:
            url: "http://127.0.0.1:7788"
          tsa:
            host: 127.0.0.1
            port: 2222

      - name: tsa
        release: concourse
        properties:
          forward_host: 127.0.0.1
          atc:
            address: 127.0.0.1:8080

      - name: baggageclaim
        release: concourse

      - name: garden
        release: garden-runc
        properties:
          garden:
            listen_network: tcp
            listen_address: 0.0.0.0:7777
            graph_cleanup_threshold_in_mb: 3072
            max_containers: 1024
            network_pool: "10.254.0.0/20"

      - name: collectd
        release: collectd
        properties:
          collectd:
            hostname_prefix: concourse_
            interval: (( grab meta.collectd.interval ))
            config: (( grab meta.collectd.config ))

    networks:
      - name: public
        static_ips:
        - (( grab terraform_outputs.concourse_elastic_ip ))
      - name: concourse
        static_ips: (( static_ips(0) ))
        default: [dns, gateway]

    properties: {}

cloud_provider:
  template: {name: aws_cpi, release: bosh-aws-cpi}

  ssh_tunnel:
    host: (( grab terraform_outputs.concourse_elastic_ip ))
    port: 22
    user: vcap
    private_key: concourse_id_rsa # Appears to be relative to working dir

  mbus: (( concat "https://mbus:" secrets.concourse_nats_password "@" terraform_outputs.concourse_elastic_ip ":6868" ))

  properties:
    aws:
      credentials_source: env_or_profile
      default_key_name: (( grab terraform_outputs.concourse_key_pair_name ))
      default_security_groups:
      - (( grab terraform_outputs.concourse_security_group ))
      - (( grab terraform_outputs.ssh_security_group ))
      region: (( grab terraform_outputs.region ))
    agent:
      mbus: (( concat "https://mbus:" secrets.concourse_nats_password "@0.0.0.0:6868" ))
    blobstore: {provider: local, path: /var/vcap/micro_bosh/data/cache}
    ntp: [0.pool.ntp.org, 1.pool.ntp.org]
