---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/terraform
    tag: cf791cec329bff5577cd8b3c9511bf89f988b5d4
inputs:
  - name: paas-cf
  - name: cf-tfstate
outputs:
  - name: updated-tfstate
run:
  path: sh
  args:
    - -e
    - -c
    - |
      cp cf-tfstate/cf.tfstate updated-tfstate/cf.tfstate

      terraform state rm -state=updated-tfstate/cf.tfstate \
        aws_iam_access_key.ses_smtp
      echo "ses smtp access key no longer managed by terraform."

      terraform state rm -state=updated-tfstate/cf.tfstate \
        aws_iam_access_key.metrics_exporter
      echo "metrics exporter access key no longer managed by terraform."

      terraform state rm -state=updated-tfstate/cf.tfstate \
        aws_iam_access_key.yace
      echo "yace access key no longer managed by terraform."

      echo "next successful deployment run will delete the unused keys"
