---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: governmentpaas/cf-cli
    tag: cf791cec329bff5577cd8b3c9511bf89f988b5d4
inputs:
  - name: config
outputs:
  - name: new-smoke-test-config
run:
  path: sh
  args:
    - -e
    - -c
    - |
      . ./config/config.sh

      NEW_SMOKE_TEST_PASSWORD=$(tr -cd '[:alpha:]0-9' < /dev/urandom | head -c32)
      TEST_CONFIG=new-smoke-test-config/smoke-test-config.json

      cat <<EOF > "${TEST_CONFIG}"
      {
        "api": "api.${SYSTEM_DOMAIN}",
        "apps_domain": "${APP_DOMAIN}",
        "user": "smoke-test",
        "password": "${NEW_SMOKE_TEST_PASSWORD}",
        "org": "continuous-smoke-test",
        "space": "continuous-smoke-test",
        "use_existing_org": true,
        "use_existing_space": true,
        "skip_ssl_validation": false,
        "artifacts_directory": "/tmp/artifacts",
        "suite_name": "CF_SMOKE_TESTS",
        "logging_app": "",
        "runtime_app": "",
        "ginkgo_opts": "",
        "backend": ""
      }
      EOF

      echo | cf login -a "${API_ENDPOINT}" -u "${CF_ADMIN}" -p "${CF_PASS}"

      cf create-org continuous-smoke-test
      cf create-space continuous-smoke-test -o continuous-smoke-test

      TEST_PASSWORD="$(jq -r .password $TEST_CONFIG)"
      TEST_ORG="$(jq -r .org $TEST_CONFIG)"
      TEST_SPACE="$(jq -r .space $TEST_CONFIG)"
      TEST_USER="$(jq -r .user $TEST_CONFIG)"

      cf t -o "${TEST_ORG}" -s "${TEST_SPACE}"
      cf delete-user "${TEST_USER}" -f # create-user isn't idempotent :-(
      cf create-user "${TEST_USER}" "${TEST_PASSWORD}"
      cf set-space-role "${TEST_USER}" "${TEST_ORG}" "${TEST_SPACE}" SpaceManager
