
- type: replace
  path: /instance_groups/name=alertmanager/persistent_disk_type?
  value: 5GB
- type: remove
  path: /instance_groups/name=alertmanager/persistent_disk

- type: replace
  path: /instance_groups/name=grafana/persistent_disk_type?
  value: 5GB
- type: remove
  path: /instance_groups/name=grafana/persistent_disk

- type: replace
  path: /instance_groups/name=prometheus2/persistent_disk_type?
  value: 100GB
- type: remove
  path: /instance_groups/name=prometheus2/persistent_disk
