- type: replace
  path: /instance_groups/name=alertmanager/instances
  value: 2

- type: replace
  path: /instance_groups/name=alertmanager/azs
  value:
    - z1
    - z2

- type: replace
  path: /instance_groups/name=prometheus2/instances
  value: 2

- type: replace
  path: /instance_groups/name=prometheus2/azs
  value:
    - z1
    - z2

- type: replace
  path: /instance_groups/name=grafana/instances
  value: 2

- type: replace
  path: /instance_groups/name=grafana/azs
  value:
    - z1
    - z2

- type: replace
  path: /instance_groups/name=firehose/instances
  value: 2

- type: replace
  path: /instance_groups/name=firehose/azs
  value:
    - z1
    - z2
